name: Publish to PyPI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

jobs:
  publish-to-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry self add poetry-bumpversion

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: poetry

      - name: Build package
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
          TAG: ${{ github.ref_name }}
        run: |
          poetry version "${TAG/v/}"
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
